services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlsql_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8388}:${APP_PORT:-8388}"
    command: [ "/app/entrypoint.sh" ]
    depends_on:
      qdrant:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: nlsql_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-8389}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 10

  wren-ui:
    build:
      context: ./wren-ui
      dockerfile: Dockerfile.dev
    container_name: nlsql_wren_ui
    restart: always
    volumes:
      - ./wren-ui:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${WREN_UI_PORT:-3003}:3000"
    environment:
      - WREN_ENGINE_URL=http://app:${APP_PORT:-8388}
    depends_on:
      - app

  qdrant:
    image: qdrant/qdrant:latest
    container_name: nlsql_qdrant
    ports:
      - "${QDRANT_EXTERNAL_PORT:-63332}:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:alpine
    container_name: nlsql_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  qdrant_data:
