
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlsql_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8388:8388"
    command: ["/app/entrypoint.sh"]
    depends_on:
      - qdrant
      - redis

  qdrant:
    image: qdrant/qdrant:latest
    container_name: nlsql_qdrant
    ports:
      - "63332:63332"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:alpine
    container_name: nlsql_redis
    ports:
      - "6379:6379"

volumes:
  qdrant_data: