FROM node:18-bookworm-slim

# Install required packages
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV development

WORKDIR /app

# Enable corepack to manage yarn versions and set the correct yarn version
RUN corepack enable

COPY .yarnrc.yml package.json yarn.lock ./
COPY .yarn/releases/yarn-4.5.3.cjs .yarn/releases/yarn-4.5.3.cjs
RUN corepack prepare yarn@4.5.3 --activate

# Install dependencies
RUN yarn install

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "dev"]
